import type { Metadata } from "next";
import { Sen } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./components/other/SessionWrapper";
const Sans = Sen({
  subsets: ['latin'],
  weight: ['500', '400', '700', '800', '600'],
});

export const metadata: Metadata = {
  title: "CRM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body
          className={`${Sans.className}  antialiased`}
          >
        <SessionWrapper>
          {children}
          </SessionWrapper>
        </body>
    </html>
  );
}
